const networkIDs = {
	MAINNET_CODE: 1,
	CLASSIC_CODE: 61,
	ROPSTEN_CODE: 3,
	RINKEBY_CODE: 4,
	GOERLI_CODE: 5,
	KOVAN_CODE: 42,
	SOKOL_CODE: 77,
	POA_CORE_CODE: 99,
	XDAI_CODE: 100,
	RSK_CODE: 30,
	RSK_TESTNET_CODE: 31,
	CELO_CODE: 42220,
	CELO_ALFAJORES_TESTNET_CODE: 44787,
	CELO_BAKLAVA_TESTNET_CODE: 62320,
}

module.exports = {
	networkIDs
}